---
- name: Run Linux commands on local node
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: linux_command
      prompt: "Please enter the Linux command you want to run"
      private: no

  tasks:
    - name: Run the specified Linux command
      command: "{{ linux_command }}"
      register: command_output

    - name: Display command output
      debug:
        var: command_output.stdout
